### ISSUE TITLE
Wishlist: support for ES6 modules.

### ISSUE THREAD

**Issue by kcoyner** [legend80s/commit-msg-linter#14]
Wishlist: support of ES6 modules.

Presently, for projects that have "type: module" in package.json, a commit will fail with the following error:

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /home/kevin/code/ftek/receiver/.git/hooks/commit-msg
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:104:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:31)
    at async Loader.import (internal/modules/esm/loader.js:176:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

**Comment by legend80s** [comment]
I am sorry, I have no good idea to support the wishlist.

**Comment by legend80s** [comment]
Came up with an idea. Working on it. 😄

**Comment by legend80s** [comment]
supported at `git-commit-msg-linter@4.0.3` 🎉
